Update merge-request-workflow.yml

diff --git a/.github/workflows/merge-request-workflow.yml b/.github/workflows/merge-request-workflow.yml
--- a/.github/workflows/merge-request-workflow.yml
+++ b/.github/workflows/merge-request-workflow.yml
@@ -41,7 +41,7 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push with commit hash tag
+      - name: Build and push Docker image
         run: |
           docker build -t example-app-image .
           docker tag example-app-image subrotosharma/node-app:${{ steps.vars.outputs.sha_short }}
@@ -51,7 +51,7 @@ jobs:
     needs: build-push-image
     runs-on: ubuntu-latest
     steps:
-      - name: Deploy to AWS EC2
+      - name: Deploy to EC2
         uses: appleboy/ssh-action@v0.1.10
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -64,7 +64,10 @@ jobs:
 
             echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
-            cd example-app-environments || { echo "❌ Folder example-app-environments not found"; exit 1; }
+            # Clean and clone repo
+            rm -rf multi-env-ci-cd-pipeline
+            git clone https://github.com/subrotosharma/multi-env-ci-cd-pipeline.git
+            cd multi-env-ci-cd-pipeline/example-app-environments || { echo "❌ Folder not found"; exit 1; }
 
             if [ -f ".env" ]; then
               source .env
